apiVersion: v1
kind: Secret
metadata:
  name: {{ include "laravel-app.fullname" . }}-secret
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
type: Opaque
data:
  DB_DATABASE: {{ .Values.mysql.database | b64enc | quote }}
  DB_USERNAME: {{ .Values.mysql.username | b64enc | quote }}
  DB_PASSWORD: {{ .Values.mysql.password | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc | quote }}

