apiVersion: v1
kind: Service
metadata:
  name: {{ include "laravel-app.fullname" . }}-web
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "laravel-app.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80

