apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-app-config
data:
  APP_NAME: "Laravel"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "http://laravel-app.local"
  APP_KEY: "base64:BTfPQTW53cN12TSA9kwq4u9pRRIoevOqrkPtFWndXDU="


