apiVersion: v1
kind: Secret
metadata:
  name: laravel-app-secret
type: Opaque
data:
  DB_DATABASE: bGFyYXZlbA==
  DB_USERNAME: bGFyYXZlbA==
  DB_PASSWORD: c2VjcmV0
  APP_KEY: ""  # можно будет заполнить позже base64-значением APP_KEY


