apiVersion: v1
kind: Service
metadata:
  name: laravel-web
  labels:
    app: laravel-web
spec:
  type: ClusterIP
  selector:
    app: laravel-web
  ports:
    - port: 80
      targetPort: 80


